# -*- coding: utf-8 -*-
"""fara_vllm_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKGTn8vxYPKxjk11llUrtLtsSmK12D8X

# VILAGENT FARA 7B Vision Model via vLLM + pyngrok

Bu notebook FARA-7B (Qwen2-VL tabanlı) modelini Colab üzerinde en stabil vLLM sürümüyle çalıştırır ve pyngrok ile dışarıya açar.

**Özellikleri:**
- Paket uyuşmazlıkları (Numpy 2.0, Protobuf, CUDA 13) tamamen giderilmiştir.
- Model Hugging Face cache üzerinden indirilir (İnmişse tekrar indirmez).
- vLLM başlamadan önce paket uyumlulukları kontrol edilir.
- Sunucu ayağa kalkana kadar HTTP Health Check ile beklenir.
"""

# 1. KURULUM
# TensorFlow ve TensorBoard, Colab'da protobuf çakışmalarına neden olduğu için öncelikle kaldırıyoruz.
!pip uninstall -y tensorflow tensorboard xformers vllm -q

# Gerekli araçlar ve uyumlu Numpy/Protobuf sürümleri
!pip install -q pyngrok huggingface_hub requests "numpy>=2.0.0" "protobuf>=4.25.0" transformers==4.47.1

# vLLM'in Colab CUDA 12 ortamında en stabil çalışan sürümü
!pip install -q vllm==0.7.3

print("\n✅ Kurulum tamamlandı.")
print("⚠️ EĞER BUNDAN SONRAKİ HÜCRELERDE 'ImportError' ALIRSANIZ, LÜTFEN 'Runtime -> Restart runtime' YAPIP 2. HÜCREDEN DEVAM EDİN.")

import os
os.kill(os.getpid(), 9)

# 2. AYARLAR VE KİMLİK BİLGİLERİ
import os
from getpass import getpass

NGROK_AUTHTOKEN = os.getenv("NGROK_AUTHTOKEN") or getpass("NGROK_AUTHTOKEN: ")
VLLM_API_KEY = os.getenv("VLLM_API_KEY") or "vilagent-secret-key"

MODEL_NAME = "microsoft/Fara-7B"
PORT = 5000

os.environ["NGROK_AUTHTOKEN"] = NGROK_AUTHTOKEN
os.environ["VLLM_API_KEY"] = VLLM_API_KEY
os.environ["HF_HOME"] = "/root/.cache/huggingface"

print(f"\nAyarlar yüklendi! Model: {MODEL_NAME}, Port: {PORT}")

# 3. ORTAM VE BAĞIMLILIK KONTROLÜ
import sys
import traceback

print("Paketler kontrol ediliyor...")
try:
    import torch
    import transformers
    import vllm
    print(f"PyTorch sürümü: {torch.__version__}")
    print(f"Transformers sürümü: {transformers.__version__}")
    print(f"vLLM sürümü: {vllm.__version__}")

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA (GPU) bulunamadı! Lütfen Colab menüsünden Runtime -> Change runtime type -> T4/L4/A100 GPU seçin.")

    print(f"Kullanılacak GPU: {torch.cuda.get_device_name(0)}")
    print("\n✅ Ortam kontrolleri başarıyla geçildi!")
except Exception as e:
    print("\n❌ KONTROL BAŞARISIZ! Paket uyumsuzluğu var.")
    traceback.print_exc(limit=5)
    print("\nÇÖZÜM: Menüden 'Runtime -> Restart runtime' yapıp direkt 2. hücreden çalışmaya devam edin.")
    raise

# 4. MODELİ İNDİRME / CACHE KONTROLÜ
from huggingface_hub import snapshot_download
import time

print(f"{MODEL_NAME} modeli indiriliyor veya cache'den yükleniyor...")
print("(İnternetten ilk indirme 3-5 dakika sürebilir, sonraki çalışmalarda cache'den 1-2 saniyede okunur.)")

start_time = time.time()
try:
    # Önce sadece cache'de var mı diye kontrol et (internet harcamamak için)
    RESOLVED_MODEL_PATH = snapshot_download(repo_id=MODEL_NAME, local_files_only=True)
    print("\n✅ Model önbellekte (cache) bulundu! İnternetten indirmeye gerek kalmadı.")
except:
    # Cache'de yoksa internetten indir
    print("\nModel cache'de bulunamadı. İnternetten indiriliyor...")
    RESOLVED_MODEL_PATH = snapshot_download(repo_id=MODEL_NAME)
    print(f"\n✅ Model başarıyla indirildi! ({time.time() - start_time:.1f} saniye)")

print(f"\nModel Yolu: {RESOLVED_MODEL_PATH}")

# 5. vLLM SUNUCUSUNU BAŞLATMA
import subprocess
import requests
import os

# Olası eski vLLM süreçlerini temizle (Port ve VRAM çakışmasını önler)
os.system("pkill -9 -f 'vllm.entrypoints.openai.api_server'")
time.sleep(2)

print("vLLM sunucusu başlatılıyor...")
cmd = [
    sys.executable, "-m", "vllm.entrypoints.openai.api_server",
    "--host", "0.0.0.0",
    "--port", str(PORT),
    "--model", RESOLVED_MODEL_PATH,
    "--served-model-name", MODEL_NAME,
    "--api-key", VLLM_API_KEY,
    "--trust-remote-code",
    "--max-model-len", "4096",
    "--dtype", "bfloat16",
    "--gpu-memory-utilization", "0.90",
    "--limit-mm-per-prompt", "image=1"
]

with open("vllm_server.log", "w") as log_file:
    server = subprocess.Popen(cmd, stdout=log_file, stderr=subprocess.STDOUT)

print(f"Sunucu PID: {server.pid}. Model VRAM'e yükleniyor...")

# Sunucunun ayağa kalkmasını HTTP isteği atarak bekle
headers = {"Authorization": f"Bearer {VLLM_API_KEY}"}
ready = False

for step in range(120): # Maksimum 10 dakika bekle (120 * 5 saniye)
    time.sleep(5)
    if server.poll() is not None:
        print(f"\n❌ Sunucu beklenmedik şekilde çöktü (Exit Code: {server.returncode}).")
        print("Son hatalar:\n")
        with open("vllm_server.log", "r") as f:
            print(f.read()[-3000:])
        raise RuntimeError("vLLM sunucusu çöktü.")

    try:
        res = requests.get(f"http://localhost:{PORT}/v1/models", headers=headers, timeout=2)
        if res.status_code == 200:
            print("\n\n✅ vLLM SUNUCUSU BAŞARIYLA AYAĞA KALKTI!")
            ready = True
            break
    except requests.exceptions.RequestException:
        pass

    print(".", end="", flush=True)

if not ready:
    print("\n❌ Sunucu zaman aşımına uğradı. Loglara bakınız.")
    raise TimeoutError("vLLM sunucusu zamanında başlatılamadı.")

# 6. PYNKGROK İLE DIŞARI AÇMA VE ÇEVRE DEĞİŞKENLERİ
from pyngrok import conf, ngrok

conf.get_default().auth_token = NGROK_AUTHTOKEN
tunnel = ngrok.connect(f"127.0.0.1:{PORT}", "http")
public_url = tunnel.public_url.rstrip("/")

print("\n======================================================")
print("🚀 BAĞLANTI HAZIR!")
print("\nAşağıdaki değerleri kendi bilgisayarınızdaki '.env' dosyasına yapıştırın:\n")

print("VILAGENT_FARA_ENABLED=true")
print(f"VILAGENT_FARA_MODEL_NAME={MODEL_NAME}")
print(f"VILAGENT_FARA_BASE_URL={public_url}/v1")
print(f"VILAGENT_FARA_API_KEY={VLLM_API_KEY}")
print("VILAGENT_VISION_PROVIDER=fara")
print("======================================================\n")

# Son bir bağlantı testi atalım:
print("Tünel Üzerinden API Testi Yapılıyor...")
res = requests.get(f"{public_url}/v1/models", headers={"Authorization": f"Bearer {VLLM_API_KEY}"})
if res.status_code == 200:
    print("✅ Dış Bağlantı Testi Başarılı!")
else:
    print(f"⚠️ Bağlantı Testi Başarısız! Status: {res.status_code}, Hata: {res.text}")

print("bırt")